### ISSUE TITLE
Sublime 3 - Gist is Not Inserted Properly

### ISSUE THREAD

**Issue by rooseveltrp** [condemil/Gist#104]
Hi,

I noticed the Gist plugin for Sublime 2 is not quite Sublime 3 ready yet. I gave it a go anyways... and noticed couple of things right away. The Keyboard shortcuts are not working from the getgo and noticed something funky while inserting a Gist.

I tried to insert this gist https://gist.github.com/rooseveltrp/6453919 but the plugin did not grab all of its contents and the formatting is quite poor.

Any updates and fixes would be greatly appreciated. It is an awesome plugin!

![snapshot1](https://f.cloud.github.com/assets/4078130/1090532/5900018e-1658-11e3-9b31-3c71a443843a.png)

**Comment by condemil** [comment]
Fixed in a6825c251c16dab33e490144054440008d75e6e3
