### ISSUE TITLE
Gist: unknown error - ST3

### ISSUE THREAD

**Issue by FStop** [condemil/Gist#114]
Each time I try to use the plugin I get the following error (in Sublime Text 3):

Gist: unknown error (please, report a bug!)

![screen shot 2013-11-18 at 12 09 00 pm](https://f.cloud.github.com/assets/1437322/1565829/10fc0510-5085-11e3-8169-2b991c6f70e8.png)

**Comment by condemil** [comment]
I believe it is not an issue anymore, in case you still have that issue you can reopen it.
