### ISSUE TITLE
GitHub returned error 404: Not Found when creating new Gist

### ISSUE THREAD

**Issue by miharp** [condemil/Gist#123]
Saw this in the closed list but having the same problem with latest version of plugin.
OS X 10.9.2
SublimeText 2.0.2 2221

**Comment by stormbytes** [comment]
same issue

OS 10.10.5

ST3

**Comment by giuseb** [comment]
Ditto, macOS 10.12.2, ST3 build 3126

**Comment by condemil** [comment]
I saw same error during github outages, in case you still have same error you can reopen the issue.
