### ISSUE TITLE
Limited to 30 gists

### ISSUE THREAD

**Issue by bcorreia** [condemil/Gist#144]
Regardless of the value under **max_gists**, the limit of gists fetched is 30. Could you please advise?

**Comment by xjsender** [comment]
See https://github.com/sanusart/gists-backup/blob/master/gist-backup.js#L26 , this plugin missed ``per_page`` parameter when retrieve all gists.

**Comment by rudiedirkx** [comment]
The problem seems to be `settings.load()` isn't run, so `GISTS_URL` isn't extended with `'?per_page=%d' % loaded_settings.get('max_gists')`.

I can't find out why not...

**Comment by rudiedirkx** [comment]
Adding this at the start of `GistListCommandBase.run()` in `gist.py` does it for me, but hacky:

```
MAX_GISTS = '?per_page=%d' % settings.loaded_settings.get('max_gists')
settings.GISTS_URL += MAX_GISTS
```

Kudos for the person than can explain to me why `settings.load()` isn't run. (I don't know Python very well, obviously.)

**Comment by xiconet** [comment]
@rudiedirkx  Same problem here, but the "hack" you provide indeed works. Thanks!

**Comment by ryanwhetstone** [comment]
Same problem here... I wasn't sure how to do what @rudiedirkx was describing, so I'm sure someone else is confused like I was, so here is what I did.
Forked this repo, updated the lines in gist.py just as he describes. Then I installed the new forked package as described here http://www.macdrifter.com/2012/08/install-sublime-packages-from-github.html
Now all my gists come in to Sublime... fantastic! 
Thanks @rudiedirkx for the fix.

**Comment by rudiedirkx** [comment]
What I did was install `PackageResourceViewer`. With that, you can edit all package and source files, like `gist.py`. It saves the altered file locally in your user dir.

**Comment by fleef-gist** [comment]
Thanks @rudiedirkx - your fix to gist.py is working for me, but weirdly only on first execution...

If I activate open gists and search, I get all gists returned.
However, if I repeat those steps, I get a shorter list of gists returned.

If I restart ST it works again, but again for one time only.  I can live with that for now.
Same thing on both ST2 and 3.

**Comment by rudiedirkx** [comment]
@fleef-gist Maybe the user that runs ST doesn't have write access in your user profile..? Search for `gist.py` in your OS' user profile. If it's not there, PRV can't persist changes. Maybe =)

**Comment by supervova-snippets** [comment]
Thx, @rudiedirkx

**Comment by Brugman** [comment]
@ryanwhetstone @rudiedirkx For me this fixed seeing 100. Do you get more than 100?

I've got the same "once only" situation. I used PackageResourceViewer to open and save gist.py and settings.py locally in Packages/Gist. @fleef-gist Did you get yours working continuously?

**Comment by rudiedirkx** [comment]
@Brugman `100` is Github's limit. I used PackageResourceViewer too, it's the best. I also [ordered by star](https://github.com/condemil/Gist/issues/144#issuecomment-58573287) so stars are always included, and up top.

**Comment by rudiedirkx** [comment]
My fix doesn't seem to be correct actually. By appending to `settings.GISTS_URL` every time, the URL will become something like

    https://api.github.com/gists?per_page=20?per_page=99?per_page=99?per_page=99?per_page=99

and if the first time the limit was `20` and then you changed it to `99` without restarting ST, it'll keep using `20`.

This is my new code:

```
MAX_GISTS = '?per_page=%d' % settings.loaded_settings.get('max_gists')
GISTS_URL = settings.GISTS_URL + MAX_GISTS
STARRED_GISTS_URL = settings.STARRED_GISTS_URL + MAX_GISTS

filtered = gists_filter(api_request(GISTS_URL))
filtered_stars = gists_filter(api_request(STARRED_GISTS_URL))
```

If you never change the config, it shouldn't be a problem.

I still don't understand why `settings.load()` doesn't run....

**Comment by JordyVR** [comment]
Same problem here. Where can i find/edit gist.py ? Want to try @rudiedirkx his solution

**Comment by rudiedirkx** [comment]
@JordyVR Install `PackageResourceViewer` to open it. It'll save the override in your OS user profile somewhere.

**Comment by JordyVR** [comment]
@rudiedirkx thanks allot, it works!
