### ISSUE TITLE
(Enterprise) Gist: GitHub returned error 401: Bad credentials

### ISSUE THREAD

**Issue by roboslone** [condemil/Gist#148]
My settings are:  

```
{
    "token": "***",
    "enterprise": true,
    "url": "https://github.***.ru",
}
```

Every time I try to create gist I get "Gist: GitHub returned error 401: Bad credentials" . Changing url to "https://api.github.***.ru" doesn't solve the problem. Token is okay, I checked it with simple curl request to API.

**Comment by jonbrenner** [comment]
That's because the plugin continues to make requests to https://api.github.com/gists, despite the configuration. I'm going to fork it and figure it out. I'll submit a pull request for @condemil after it's done.

**Comment by chrisfowler** [comment]
Did this ever get solved? Am having the issue with similar enterprise setting as RoboSloNE listed.
