### ISSUE TITLE
Error: "Gist: unknown error (please, report a bug!)"

### ISSUE THREAD

**Issue by warrenkeith** [condemil/Gist#151]
Post-install when trying to do anything with Gist! No settings popup.

**Comment by knjname** [comment]
I faced this problem (Win8.1 x64 and Sublime 2.0.2),

```
Traceback (most recent call last):
  File ".\gist.py", line 37, in _fn
    return fn(*args, **kwargs)
  File ".\gist.py", line 209, in on_gist_filename
    gist = create_gist(self.public, description, gist_data)
  File ".\gist.py", line 60, in create_gist
    gist = api_request(settings.GISTS_URL, data)
  File ".\request.py", line 135, in api_request
    return api_request_curl(url, data, token, https_proxy, method)
  File ".\request.py", line 49, in api_request_native
    token = token if token != None else token_auth_string()
  File ".\request.py", line 39, in token_auth_string
    raise MissingCredentialsException()
MissingCredentialsException
error: Gist: unknown error (please, report a bug!)
```

and the following lines seem not to work.

```python
at request.py line 32.

def token_auth_string():
    settings = sublime.load_settings('Gist.sublime-settings')
    token = settings.get('token')
    print settings.get('token') # -> "None"
    print settings.get('max_gists') # -> "None"

```

**Comment by lasselehtinen** [comment]
Same problem, but with Win7 x64 and Sublime Text 2.0.2. Token has been created and added to the config.

```
Traceback (most recent call last):
  File ".\gist.py", line 37, in _fn
  File ".\gist.py", line 209, in on_gist_filename
  File ".\gist.py", line 60, in create_gist
  File ".\request.py", line 135, in api_request
  File ".\request.py", line 47, in api_request_native
  File ".\request.py", line 37, in token_auth_string
MissingCredentialsException
error: Gist: unknown error (please, report a bug!)
```

**Comment by adiaz101** [comment]
For those also not being able to open a gist, change the "show_authors":  to false. Running on windows 7

**Comment by properdesign** [comment]
+1 to everyone above who suggested changing "show_authors" to false. Worked for me on OSX 10.10

**Comment by leongaban** [comment]
http://stackoverflow.com/questions/28972615/gist-plugin-erroring-out-in-sublime-text-3?noredirect=1#comment46196521_28972615

The plugin still produces the same error for me. OSX Yosemite + Sublime Text 3.

I generated the token, and added it along with the `"show_authors": false` flag :(

**Comment by leongaban** [comment]
Got it working!

Instead of generation a token via the CURL command: https://github.com/condemil/Gist#generating-access-token

I had to generation a token on Github here: https://github.com/settings/applications#personal-access-tokens

It produced a string which I pasted into the "token" key instead of the JSON produced by the CURL command.

**Comment by daynaskully** [comment]
Sublime 2.0.2, 2221 (osx 10.10.2)

MissingCredentialsException: Doesn't read Gist.sublime-settings to get the access token. If i edit request.py and manually return my token it works.

```
from pprint import pprint
pprint (vars(settings))
```
{}

**Comment by ianchanning** [comment]
Since the proper settings window doesn't open on package installation. When you add your token make sure you are editing 

*Preferences > Package Settings > Gist > Settings - User* 

and not just 

*Preferences > Settings - User*

**Comment by spleenteo** [comment]
I don't know why and how but at the first line of my gist user preference file, there is a path to the file it self. I've just removed that line, and now it works like a charm.

**Comment by schutzsmith** [comment]
Took the advice of all above but still doesn't seem to work. Even made new token via Personal Access. Any other possible solutions?

**Comment by llanquin** [comment]
i took all the advices too but nothing seemed to work until i noticed my gist user preferences had some elements inside [ ] and they were not an array so i eliminated it and now is working.

the lines where: 

    "include_users": "[llanquin]" and "include_orgs": "[]", 

and i changed them to:

    "include_users": "llanquin" and "include_orgs": "",

hope this simple and stupid thing can help other people

**Comment by drebbits** [comment]
[This](https://github.com/condemil/Gist/issues/151#issuecomment-66763858) solved it for me. Just wondering why the Settings - Default isn't editable?

**Comment by kevin-snippet** [comment]
put in the token and it works :)

**Comment by phaberest** [comment]
I can confirm it still gives that error if I set `"show_authors": true`, solved with @mhanel hint.

**Comment by rocketmannot** [comment]
@emrecamasuvi solution is working

**Comment by versedi** [comment]
@mhanel's solution is a way to go :+1:

**Comment by ouinon** [comment]
@ianchanning +1. It was just a matter of knowing where to set the token.

**Comment by Unayung** [comment]
@mhanel kudo for that !! just turn show_authors to false and voila :)

**Comment by eteache** [comment]
@emrecamasuvi :+1:

**Comment by mvexel** [comment]
The solution @mhanel provided also works on Linux.
