### ISSUE TITLE
Getting 2 error alerts while trying to change description ("uknown error" & "GitHub returned error 401")

### ISSUE THREAD

**Issue by eyalzek** [condemil/Gist#158]
Creating Gists works great, opening and updating them works great. 
When I try to change the description of a gist, I get these 2 alerts; first of all the "unknown error (please, report a bug!)"  and underneath it, a second alert which says I have bad credentials.

This strikes me as weird, because my credentials are obviously fine if I'm able to do all other operations.

**Comment by condemil** [comment]
Thank you for your contribution!
