### ISSUE TITLE
Installation problems - cannot add token/edit settings

### ISSUE THREAD

**Issue by TomoGlavas** [condemil/Gist#161]
Hi,

I cannot edit the settings where the token should go. Tried to edit file directly, and it seems the plugin placed settings into 
/Users/Me/Library/Application Support/Sublime Text 3/Packages/Gist/Gist.sublime-settings
While I'm using Sublime Text 2.

Settings file is read-only, probably due to permissions.

**Comment by walkerdigital** [comment]
Since you were able to close this issue same day I assume you figured out the problem.  I too am unable edit the token and I'm wondering what your solution was.  I'm on OSX El Capitan

Thanks

**Comment by walkerdigital** [comment]
n/m  - I was able to copy only the token setting into my User Settings and it worked.  Couldn't edit the default settings.

`{
    // Your GitHub API token
    // see: https://github.com/condemil/Gist#generating-access-token
    "token": "#######################################"

}`
