### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by jrock2004** [condemil/Gist#163]
So at work we use an open source alternative called gitlab. Gitlab has gists but its a little different. Is there anyway to add support?

``` bash
Here is an example url https://gitlab.myworkdomain.net/snippets/74
```

Thanks

**Comment by condemil** [comment]
Sublime Gist project is highly integrated with features provided by GitHub, as I can see GitLab Snippets may look similar, however they have core deferences, such as only one file per snippet or completely different API that makes it challenging to support both within one project. As a good start you or someone else may fork Sublime Gist and adapt it for GitLab Snippets.
