### ISSUE TITLE
Problems with SB3 and Gist on Mac OS El Capitan

### ISSUE THREAD

**Issue by robertovg** [condemil/Gist#175]
I have Mac OS X 10.11.5 (El Capitan ) , Sublime Text Editor 3 (3114) and I just installed Gist. I'm getting the following exception:

`unloading plugin Gist.gist
reloading settings Packages/Gist/Gist.sublime-settings
unloading plugin Gist.helpers
unloading plugin Gist.request
unloading plugin Gist.settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/robertovazquezgonzalez/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
Package Control: The package Gist has been removed
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: []
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/robertovazquezgonzalez/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/robertovazquezgonzalez/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Git.sublime-settings
reloading settings Packages/User/Git.sublime-settings
ignored packages updated to: ["Gist"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/robertovazquezgonzalez/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
ignored packages updated to: []
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin Gist.gist
reloading settings Packages/Gist/Gist.sublime-settings
reloading plugin Gist.helpers
reloading plugin Gist.request
reloading plugin Gist.settings
reloading /Users/robertovazquezgonzalez/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/robertovazquezgonzalez/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "gist in /Users/robertovazquezgonzalez/Library/Application Support/Sublime Text 3/Installed Packages/Gist.sublime-package", line 37, in _fn
  File "gist in /Users/robertovazquezgonzalez/Library/Application Support/Sublime Text 3/Installed Packages/Gist.sublime-package", line 327, in run
  File "request in /Users/robertovazquezgonzalez/Library/Application Support/Sublime Text 3/Installed Packages/Gist.sublime-package", line 135, in api_request
  File "request in /Users/robertovazquezgonzalez/Library/Application Support/Sublime Text 3/Installed Packages/Gist.sublime-package", line 47, in api_request_native
  File "request in /Users/robertovazquezgonzalez/Library/Application Support/Sublime Text 3/Installed Packages/Gist.sublime-package", line 37, in token_auth_string
Gist.request.MissingCredentialsException
error: Gist: unknown error (please, report a bug!)`

I have created the `/Users/user/Library/Application Support/Sublime Text 3/Packages/User/Git.sublime-settings` file and added the token generated on github, but still the exception stay.

Also I have re-installed it a couples time with the same result.

If someone can help here will be very appreciated.

Thanks in advance.

**Comment by condemil** [comment]
It should be `Gist.sublime-settings`, not `Git.sublime-settings`. It is useful to use menu `Sublime Text` -> `Preferences` -> `Package Settings` -> `Gist` -> `Settings - User` instead of manually creating the files.
