### ISSUE TITLE
Sublime Text 3: unknown error 

### ISSUE THREAD

**Issue by skylock** [condemil/Gist#185]
OS: 
OS Version: 
Sublime Text Version: 3

Gist User Settings (without your secret token):
{
    // Your GitHub API token
    // see: https://github.com/condemil/Gist#generating-access-token
    "token": "",

    // Show GitHub organizations
    // Example: "company1", "company2"
    "include_orgs": [],

    // Show GitHub users
    // Example: "user1", "user2"
    "include_users": [],

    // Show the authors of Gists
    "show_authors": false,

    // Prefer first file name instead of description in Open Gist menu
    "prefer_filename": false,

    // Proxy server
    // Format: "http://user:pass@proxy:port"
    "https_proxy": "",

    // Enterprise support
    "enterprise": false,
    // Github URL
    // Default: Leave empty if you want to use GitHub.com
    // Example: https://github.domain.com
    "api_url": "https://api.github.com",

    // Max Gists to show (max 100 allowed by GitHub API)
    "max_gists": 100,

    // Only use starred gists
    "use_starred": false,

    // Disable the "save file..." dialog when closing a Gist
    "supress_save_dialog": true,

    // Update the Gist upon saving the file, suppressing the filename dialog.
    "save-update-hook": true

    // Limit to gists with specific prefix
    //"gist_prefix": "Snippet:",

    // Limit to gists with specific tag (#tag)
    //"gist_tag": "snippet"
}

Steps to reproduce the issue:

Try to open gist using the plugin

Additional information (error message / screenshot):

Traceback (most recent call last):
  File "E:\Kit\Utils\Sublime Text 3\Data\Packages\gist\gist_80.py", line 55, in _fn
    return fn(*args, **kwargs)
  File "E:\Kit\Utils\Sublime Text 3\Data\Packages\gist\gist_80.py", line 328, in run
    filtered_not_stared = gists_filter(api_request(settings.get('GISTS_URL')))
  File "E:\Kit\Utils\Sublime Text 3\Data\Packages\gist\gist_60_helpers.py", line 63, in gists_filter
    name = gist_title(gist)
  File "E:\Kit\Utils\Sublime Text 3\Data\Packages\gist\gist_60_helpers.py", line 40, in gist_title
    title = list(gist['files'].keys())[0]
IndexError: list index out of range
error: Gist: unknown error (please, report a bug!)

**Comment by valdevweb** [comment]
same error

**Comment by Franklyn1987** [comment]
how to save it
