### ISSUE TITLE
Gist: GitHub returned error 401: Bad credentials

### ISSUE THREAD

**Issue by dave-hunt** [condemil/gist#21]
No matter what I try to do with this plugin, I get the error:

Gist: GitHub returned error 401: Bad credentials

I'm using OS X, and I've tried adding the credentials to my keychain and to the settings file. I've tried multiple accounts and passwords as well, and I still get the error. 

Even when I remove the plugin and add it again, same issue occurs, and it never prompts me to add my information to the settings file (like it says in the readme)

**Comment by wcervini** [comment]
doesn't work

**Comment by max-men** [comment]
having that issue with android studio too

**Comment by rameshboyee-shadkona** [comment]
![image](https://user-images.githubusercontent.com/66171963/83391197-be751e80-a410-11ea-9476-ff473d80fde6.png)
This is my problem how to solve this

**Comment by condemil** [comment]
This plugin is for Sublime Text, not Android Studio.

**Comment by smartmoveplanning** [comment]
I am having issues. I read all the responses but I am new to working on software. Can someone please explain to me step by step where to fix the problem. i cannot login as everyone couldnt
