### ISSUE TITLE
Gist: GitHub returned error 404: Not Found

### ISSUE THREAD

**Issue by jdfsoftware-gists** [condemil/gist#80]
Whenever creating or updating a Gist I get the error:
"Gist: GitHub returned error 404: Not Found"

Settings are correct, API key is correct. I can view and retrieve my web-created gists without a problem, but I cannot create a new gist nor update an existing gist.

Sublime Text 2.0.1 Build 2217
Linux Mint

**Comment by giuseb** [comment]
I installed the plugin today, experiencing exactly the same problem...
Sublime Text 3, build 3126

**Comment by salmaanahmed** [comment]
Seems like gists are not saving again

**Comment by condemil** [comment]
Based on https://status.github.com/messages the GitHub was down during that period of time.
